### ISSUE TITLE
fix loading plugin with Trac 1.4.x

### ISSUE THREAD

**Issue by aroth-arsoft** [aroth-arsoft/trac-crashdump#2]
2020-02-17 18:41:33,229 Trac[loader] DEBUG: Loading plugin "crashdump.api" from "/usr/local/lib/python2.7/site-packages/TracCrashDump-0.45-py2.7.egg"
2020-02-17 18:41:33,230 Trac[loader] DEBUG: Loading plugin "crashdump.submit" from "/usr/local/lib/python2.7/site-packages/TracCrashDump-0.45-py2.7.egg"
2020-02-17 18:41:33,231 Trac[loader] ERROR: Skipping "crashdump.submit = crashdump.submit": ImportError: cannot import name HTTPInternalError
2020-02-17 18:41:33,231 Trac[loader] DEBUG: Loading plugin "crashdump.web_ui" from "/usr/local/lib/python2.7/site-packages/TracCrashDump-0.45-py2.7.egg"
2020-02-17 18:41:33,232 Trac[loader] ERROR: Skipping "crashdump.web_ui = crashdump.web_ui": ImportError: No module named genshi.builder

**Comment by aroth-arsoft** [comment]
Another error is 
`2020-02-23 18:04:36,088 Trac[env] ERROR: Component <Component crashdump.api.CrashDumpSystem> failed with 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/trac/env.py", line 387, in component_guard
    yield
  File "/usr/local/lib/python2.7/site-packages/trac/env.py", line 750, in needs_upgrade
    if participant.environment_needs_upgrade():
TypeError: environment_needs_upgrade() takes exactly 2 arguments (1 given)
`

which is the same as in https://trac.edgewall.org/ticket/12612
